FROM python:3.12-alpine

# Install dependencies
RUN pip install celery

WORKDIR /usr/src/app

# Copy the Celery configuration file if you have one
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Entry point
CMD ["celery", "-A", "app", "worker", "--loglevel=info"]
